### PR TITLE
fix(b2b-nextjs): changes for V2 and switch to Personal Access Token

### PR DESCRIPTION
**Pull request by peintnermax**
- [x] Terminate session on logout
- [x] Edit Profile -> Should redirect to the users profile in their org (eg, a customer org); no additional account selection
- [x] Navi: Link to console should link to the issuer console
- [x] Timestamp on browser calls for debugging

### CODE REVIEW

**Comment by mffap** [comment]
@peintnermax please have a look at
- [ ] Edit Profile -> Should redirect to the users profile in their org (eg, a customer org)
- [ ] Navi: Link to console should link to the issuer console

**Comment by mffap** [comment]
@peintnermax the logout button does not seem to terminate the session on zitadel. I can login without a typing in my password.

- [ ] Terminate session on logout

**Comment by mffap** [comment]
I think the current state is broken (by me). Might be some issue with renaming API to ZITADEL_API. Need to check this out later.

**Comment by mffap** [comment]
@fforootd for your reference. This is the update demo with docs for v2

**Comment by peintnermax** [comment]
I've changed links to console and user, called endsession endpoint, and added the timestamps.
Changes in README are a prefix for `ZITADEL_ISSUER` such that the variable can be called from clientside and adding the `localhost:3000` as post redirect as its required for end_session endpoint 👍

**Review by mffap — APPROVED** [review]

**Pull request merged**
